# numpy ndarray
- numpy는 특히 벡터 및 행렬 연산에 있어 편의성을 제공하는 라이브러리
- numpy에서는 기본적으로 array(어레이)라는 단위로 데이터를 관리하고, 이에 대한 연산을 수행

# 1차원 array

In [2]:
import numpy as np

In [6]:
data = [6,7.5,8,0,1]

In [7]:
arr1 = np.array(data)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [8]:
arr1.shape

(5,)

In [9]:
arr = np.array([2,3,4])
arr

array([2, 3, 4])

# 2차원 array

In [10]:
data2 = [[1,2,3,4],
         [5,6,7,8]]
data2

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [11]:
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
arr2.shape

(2, 4)

# zeros(), ones(), arange() 함수

In [13]:
# zeros는 0으로 된 array를 만든다
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [15]:
# ones는 1로된 array를 만든다
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
# arange는 연속된 수로 array를 만든다
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
arr1.dtype

dtype('float64')

In [18]:
arr2.dtype

dtype('int64')

In [19]:
# 데이터 타입을 직접 지정할 수 있음
arr = np.array([1,2,3,4,5], dtype=np.int64)
arr

array([1, 2, 3, 4, 5])

In [21]:
arr.dtype

dtype('int64')

In [22]:
# 기존의 타입을 변경(astype())
float_arr = arr.astype(np.float64)
float_arr

array([1., 2., 3., 4., 5.])

# array 관련 연산
두 array 간에는 더하기, 빼기, 곱하기, 나누기 등의 연산을 수행할 수 있다. 동일한 위치의 성분끼리 이루어지게 되므로, 당연히 두 array의 모양이 같아야 계산이 가능하다

In [28]:
arr1 = np.array([[1,2,3],[4,5,6]], dtype=np.float64)
arr2 = np.array([[7,8,9],[10,11,12]], dtype=np.float64)

In [24]:
arr1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [25]:
arr2

array([[ 7.,  8.,  9.],
       [10., 11., 12.]])

In [26]:
# 2차원에서 같은 위치의 성분끼리 연산이 된다.
arr1 + arr2

array([[ 8., 10., 12.],
       [14., 16., 18.]])

In [29]:
arr1 * arr2

array([[ 7., 16., 27.],
       [40., 55., 72.]])

In [30]:
arr1 ** arr2

array([[1.00000000e+00, 2.56000000e+02, 1.96830000e+04],
       [1.04857600e+06, 4.88281250e+07, 2.17678234e+09]])

In [31]:
1 / arr1

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])