In [2]:
import numpy as np

In [2]:
arr = np.arange(10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr[5]

np.int64(5)

In [5]:
arr[5:8]

array([5, 6, 7])

In [6]:
arr[5:8] = 12

In [7]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [8]:
arr[:]

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

# 2차원 array 인덱싱

In [9]:
arr2 = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [13,14,15,16]])

In [12]:
# 2행의 전체값 가져오기
arr2[2, :]

array([ 9, 10, 11, 12])

In [13]:
# 1행 ~ 2행의 전체값 가져오기
arr2[1:3, : ]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
# 전체 행을 가져오되, 마지막 열 값만 가져오기
arr2[:, 3]

array([ 4,  8, 12, 16])

In [15]:
arr2[:, -1]

array([ 4,  8, 12, 16])

In [19]:
# 0~1행까지 1~2열까지의 값만 가져오기
arr2[:2, 1:3]

array([[2, 3],
       [6, 7]])

# 불리언 인덱싱

In [3]:
names = np.array(['AAA','BBB','CCC','AAA','BBB','CCC','CCC'])
data = np.random.randn(7,4)

In [4]:
names

array(['AAA', 'BBB', 'CCC', 'AAA', 'BBB', 'CCC', 'CCC'], dtype='<U3')

In [5]:
data

array([[ 1.09876615e+00,  1.05430943e+00, -4.68131104e-01,
         1.05786750e+00],
       [-1.04792979e+00,  7.46337729e-01,  1.71093527e+00,
         2.03081555e+00],
       [-5.07565022e-01, -1.69089873e+00,  1.20926864e-02,
        -8.07257137e-02],
       [-1.70889687e+00, -5.32842929e-01,  8.31772096e-01,
        -6.68952001e-01],
       [ 1.34489997e+00, -1.03564216e+00,  2.62737882e-01,
         2.61876222e-01],
       [ 1.56095056e+00,  8.80396990e-01, -3.23613660e-01,
        -2.12835897e+00],
       [ 8.14054893e-04,  1.35065332e+00,  6.87883593e-01,
         1.84095060e-01]])

In [6]:
'''
names array와 data array의 각 행에 순서대로 대응된다고 가정 인덱싱 진행
'''

'\nnames array와 data array의 각 행에 순서대로 대응된다고 가정 인덱싱 진행\n'

In [7]:
names == 'CCC' # 값이 CCC인 성분의 위치에는 True, 그 외의 위치에는 False로 확인

array([False, False,  True, False, False,  True,  True])

In [8]:
data[names=='CCC', :]

array([[-5.07565022e-01, -1.69089873e+00,  1.20926864e-02,
        -8.07257137e-02],
       [ 1.56095056e+00,  8.80396990e-01, -3.23613660e-01,
        -2.12835897e+00],
       [ 8.14054893e-04,  1.35065332e+00,  6.87883593e-01,
         1.84095060e-01]])

In [9]:
# aaa 또는 ccc의 마스크를 이용하여 array 인덱싱하기
data[(names == 'AAA') | (names == 'CCC'), : ]

array([[ 1.09876615e+00,  1.05430943e+00, -4.68131104e-01,
         1.05786750e+00],
       [-5.07565022e-01, -1.69089873e+00,  1.20926864e-02,
        -8.07257137e-02],
       [-1.70889687e+00, -5.32842929e-01,  8.31772096e-01,
        -6.68952001e-01],
       [ 1.56095056e+00,  8.80396990e-01, -3.23613660e-01,
        -2.12835897e+00],
       [ 8.14054893e-04,  1.35065332e+00,  6.87883593e-01,
         1.84095060e-01]])

In [10]:
# 조건부 마스크
data[:,3] < 0

array([False, False,  True,  True, False,  True, False])

In [11]:
data[data[:,3] < 0, :] = 1

In [12]:
data

array([[ 1.09876615e+00,  1.05430943e+00, -4.68131104e-01,
         1.05786750e+00],
       [-1.04792979e+00,  7.46337729e-01,  1.71093527e+00,
         2.03081555e+00],
       [ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
         1.00000000e+00],
       [ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
         1.00000000e+00],
       [ 1.34489997e+00, -1.03564216e+00,  2.62737882e-01,
         2.61876222e-01],
       [ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
         1.00000000e+00],
       [ 8.14054893e-04,  1.35065332e+00,  6.87883593e-01,
         1.84095060e-01]])